# Menu
menu:
  首页: /
  归档: /archives
  相册: /gallery
  关于: /about
rss: /atom.xml


# Miscellaneous
favicon: /favicon.ico
brand: /images/favicon.ico

# Ocean Video
# Because I put videos in multiple formats on the same path, I just labeled the path here.
ocean:
  overlay: true
  path: /images/ocean/
  brand: /images/favicon.ico

# Content
excerpt_link: 详细设计
# share_text: 分享
nav_text:
  page_prev: 上一页
  page_next: 下一页
  post_prev: 前一篇
  post_next: 后一篇

# fancybox
fancybox: true

# RSS
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date

# Local search
search_text: 搜索
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  unescape: true

# Gitalk
gitalk:
  enable: false # true
  clientID: 3d622004bedea7fd681f # GitHub Application Client ID
  clientSecret: e911d887db05c72d578992929c8e69352110d4fe # Client Secret
  repo: songsimen.github.io # Repository name
  owner: songsimen # GitHub ID
  admin: songsimen # GitHub ID
  createIssueManually: true
